apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Prometheus-PRD
    type: prometheus
    access: proxy
    url: https://thanos-querier-openshift-monitoring.apps.ocp.prd.detran.rj.gov.br
      #isDefault: true
    editable: false

    jsonData:
      httpHeaderName1: Authorization
      tlsSkipVerify: true

    secureJsonData:
      httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJXdVhPMklBMnNXUWRrbnZ1Nm82eWJhMU40MVBocGdTSF9UM2tCM1I0Q28ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJyaGFtcSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2UtYWNjb3VudC10b2tlbi04cHd4ayIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJncmFmYW5hLXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjMwZTI1ZTQwLWU4ZDctNGMyZS05ZTRjLTc2OWJjMzRmZTE4MyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpyaGFtcTpncmFmYW5hLXNlcnZpY2UtYWNjb3VudCJ9.OH1aR9be4QkePaaKqg9msNITX7mABDph88qFJiCtqO0YOwaKYh2RehiZpkrlGenZfOMCZ26qqbLqtHEr9kXoiskPwnss0IecQAFHqnrcxVGDRvShpEe8xcYoHJbwdVIhN3NvjKKGFSKDiEXjqr6tFKMBFUN6S7YeTsSrmGSH3j9-Eqp7QdOQW7_vMz9aRCW1f1biIz6vzh8gIGd-2PNt2-m7aHeZUAh4AtrOp_N7XfobUwRqr0GksvoxNa5c1XtNe6oB_xx1nGyKwr_TpisQX8TkvwTkDOBYvci26yrvDzF5fLdAmPCaxuMcUItqAPt8LPC46IQf3hG3Ln0t4OGrwXmhBzfqowQ3zGX6sJxAc9QwT2lRjH6KVRAwh6V1tz1fmO97OTe_pOWvMs08M9Hp6_85q22-T6T34MCY4_Rz5gTlktEXJXE5t1sy-4rEXB_yyAM9aS0FjCdwjUSR4lbfrwZvqKcfd4QeqED5Wgs5pYsdVc6-CUsUWyY1mNiRklydtbdUl2zKPsreJgctoenJQGlsNH2Hmy32iX6u9_H4muaebuqB24sArlD8u21cQ8KWjKLRJrww7G1yPHOMxy--0aRjcVFdROo-z1szmuTrHFKyI_JVY6wPqOAE9vzNw-_mSpqTNJrKbxnNRFz_plOwiwQonB25Ew15aSK_ArZ3szc"      

